name: yoloenv
channels:
  - bioconda
  - conda-forge
dependencies:
  #3.10 needed for plantcv v3.14.3
  - python=3.11
  - ipympl
  - pyarrow
  - openpyxl
  - pandarallel
  - boto3
  - pip
  - pip:
    - ultralytics
    - ultralyticsplus
    - deepsparse[yolov8,yolo,onnxruntime]
    - onnxruntime
    - onnx
